### ISSUE TITLE
Overloading WebApiCoreContoller Authorise Attribute

### ISSUE THREAD

**Issue by nrbps** [Avanade/Beef#31] opened 2020-04-27 02:22 UTC
It would be helpful if possible to enhance the generation of the WebApiCoreContollers to allow for overloads to be set on the Authorise Attribute. Currently at the controller level the only options available are "Authorize" and "AllowAnonymous". 

The only available work around I've found is at an Operation level where you can set the authorised attribute as any string ("Authorize(Policy = "BearerB2C")") for example and it will be substituted in.

If similar functionality was available at the controller level that would be ideal, otherwise if we don't want it that open, allowing custom "Policy" and "AuthenticationSchemes" overloads to be set would be a good alternative.

**Comment by chullybun** [comment] 2020-04-28 17:33
Hi. Yes, the current behavior you have observed is by design. I agree that being able to further pass a Policy would be helpful. In the meantime, as a workaround, given the Controller class is defined as a `partial` class you could create a non-generated version of the class and implement similar to the following to achieve:

``` csharp
[Authorize(Policy = "BearerB2C")]
public partial class XxxController { }
```

**Comment by chullybun** [comment] 2020-05-06 18:35
I'll assume that this issue has been resolved with the work-around described above as there has been no further correspondence.

**Closed by chullybun** 2020-05-06 18:35 UTC
