### ISSUE TITLE
feature request: Casbin.NET integration

### ISSUE THREAD

**Issue by kayamax** [Avanade/Beef#92] opened 2020-12-01 19:37 UTC
what do you think about it? any plans? hints, tips?

**Comment by chullybun** [comment] 2020-12-01 21:57
Hi @kayamax. To be fair, I don't know a lot about [_Casbin.NET_](https://github.com/casbin/Casbin.NET) - I have just done a quick read up about it.

In summary _Beef_ is largely agnostic, by design, regarding authentication and authorization. It looks as if _Casbin_ is focused on authorization, so I will respond to that directly.

There is a concept of either _Role_ or _Permission_ in _Beef_ that can be used to authorize; however, _Beef_ has no specific underlying implementation - this is up to the developer to implement. Within the [`ExecutionContext`](https://github.com/Avanade/Beef/blob/master/src/Beef.Core/ExecutionContext.cs) there are `virtual` methods `IsInRole` and `IsAuthorized` that can be overridden to implement.

Differences:
- _Role_ is expected to be a string, e.g. '`Manager`' that would be checked against a list of known roles for the authenticated user.
- _Permission_ is meant for more '`Entity.Action`' style checking; where the `Entity` is the object being checked, and the action being what is being performed e.g. `Read, Create, Update, Delete`, etc. So a _Permission_ could be `Person.Create` for example. The value, structure, format of this is entirely up to the developer; as is the underlying code to validate the value.

There are attributes/properties within the `Entity.xml` on the `Entity` and `Operation` objects to set the value; then the appropriate `ExecutionContext` method will be invoked.

Looking at the _Casbin_ it is based around `{subject, object, action}`. This seems like a logical fit for the _Beef Permission_, where `subject` is the `user`, `object` is the `Entity`, and `action` is the `Action`. Plus it also looks like _Casbin_ has the concept of _Role_ as well.

As you can see you should be able integrate _Casbin_ into _Beef_ using the generic capabilities that current exist. If, this does not suit, what do you think extra is needed to support?

Cheers...

**Comment by kayamax** [comment] 2020-12-05 15:56
thx for detailed reply chullybun, I wonder if there is any feature to reverse generate from existing mysql database? how does best practices look like??

**Comment by chullybun** [comment] 2020-12-07 19:35
@kayamax, _Beef_ as a runtime is agnostic to the data source and leverages the likes of Entity Framework which is compatible with MySQL, PostgreSQL, etc. The primary component of _Beef_ that is mostly SQL Server specific is the Database management and related code-gen; so for MySQL you could exclude its usage and leverage the primary components of _Beef_. If there was specific demand, then we could engage in extending if this was beneficial. Cheers...

**Comment by kayamax** [comment] 2020-12-08 08:24
Sorry I think, I was not specific enough with my question/request, what is the best practices for "database first" variant? is there any tool generating draft datasource(dsl.xml) from existing db-schema? BR

**Comment by chullybun** [comment] 2020-12-08 16:24
Hi. There is no official tool for generating "database first" per se. I believe there should be a formal level of separation between the entity that is being exposed and the underlying data repository. This allows the data to naturally evolve between the two as necessary. Plus, data within a database is simply a row, with one or more columns - there is no real structure or nesting to the data which can be achieved, that is more natural within an API entity. Having said that I have seen folks do a one-off generation of the `Entity.xml` based on the database to help accelerate - however, there is nothing out-of-the-box to do that.

**Closed** 2020-12-17 01:12 UTC
Labels: good first issue, question
